[package]
name = "tentacle-secio"
version = "0.2.2"
license = "MIT"
description = "Secio encryption protocol for p2p"
authors = ["piaoliu <441594700@qq.com>", "Nervos Core Dev <dev@nervos.org>"]
repository = "https://github.com/nervosnetwork/p2p"
keywords = ["network", "peer-to-peer"]
categories = ["network-programming", "asynchronous"]
edition = "2018"
build = "build.rs"

[package.metadata.docs.rs]
features = [ "molc" ]
all-features = false
no-default-features = true

[dependencies]
bytes = "0.5"
futures = { version = "0.3.0" }
tokio = { version = "0.2.0", features = ["time", "io-util", "tcp", "dns"] }
tokio-util = { version = "0.2.0", features = ["codec"] }
log = "0.4.1"

flatbuffers = { version = "0.6.0", optional = true }
flatbuffers-verifier = { version = "0.2.0", optional = true }
molecule = { version = "0.4.0", optional = true }

secp256k1 = "0.17"
rand = "0.6"
ring = "0.16.5"
unsigned-varint = "0.2.2"
bs58 = "0.3.0"

[target.'cfg(unix)'.dependencies]
openssl = "0.10.25"
openssl-sys = "0.9"

[dev-dependencies]
env_logger = "0.6"
criterion = "0.3"

[features]
default = []
# use flatbuffer to handshake
flatc = [ "flatbuffers", "flatbuffers-verifier" ]
# use molecule to handshake
molc = [ "molecule" ]

[[bench]]
name = "bench"
harness = false
